- name: Update page
  hosts: all
  become: true
  tasks:
    - name: copy index.html
      copy: 
        src=index.html 
        dest=/usr/share/nginx/html/index.html
        mode=0644
      notify:
        - Restart nginx
    - debug:
        msg: 'Page updated'
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
