- name: Echoing Vars
  hosts: all
  tasks:
    - name: Echo var
      ansible.builtin.command: /bin/echo "The username is {{username}} and the password {{password}}"
      register: response 
    - name: Print result
      debug:
        var: response
