---
- name: rhel-servers
  hosts: rhel-servers
  become: true

  tasks:
  - name: install apache
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: install postgres
    ansible.builtin.yum:
      name: postgresql-server
      state: latest

  - name: Ensure database service is starting
    ansible.builtin.service:
      name: postgresql.service
      state: started
