- name: Install ngnix
  hosts: all
  become: true
  tasks:
  - name: Get the distribution
    set_fact:
      distribution: "{{ ansible_facts['distribution'] }}"
    register: distribution_result
  - name: Print distribution
    debug:
      var: distribution_result 
  - name: install nginx in Redhat
    dnf:
      name: nginx
    when: distribution == "RedHat"
  - name: install nginx in Debian
    apt:
      name: ngnix
    when: distribution == "Debian"
