- name: CustomModule
  hosts: web 

  tasks:
    - name: executes custom module
      hello: 
        name: "Mohamed" 
      register: demo_greeting 
    - name: dump output
      debug: 
        msg: "{{ demo_greeting }}\n"
